osx_image:       xcode8.1
language:        objective-c
xcode_scheme:    OrighinateTheme
xcode_sdk:       iphonesimulator10.

rvm:
  - 2.2

install:
  - bundle install

script:
  - python -m unittest discover -s ../OriginateTheme/Scripts -p "*_test.py"
  - bundle exec scan --scheme "OriginateTheme" --clean
