osx_image:       xcode8.1
language:        objective-c
xcode_scheme:    OrighinateTheme
xcode_sdk:       iphonesimulator10.

rvm:
  - 2.2

install:
  - bundle install

script:
  - bundle exec fastlane test
