osx_image:       xcode8.1
language:        objective-c
xcode_scheme:    OriginateTheme
xcode_sdk:       iphonesimulator10.1

cache:
  - bundler

python:
  - "2.7"

rvm:
  - 2.2

install:
  - bundle install

script:
  - python -m unittest discover -s ../OriginateTheme/Scripts -p "*_test.py"
  - bundle exec scan --scheme "OriginateTheme" --clean
